ForecastPeriod: 2050
Economies: 21_VN
Scenario: Current #Current or Announced
Solver: glpk # glpk or cbc
Name: CombinedDemands #Sector(s)vX.Y.Z; Sectors = AGR,BLD,IND,POW,REF,SUP,TRN,OWN,ALL
FilePaths:
    A: '../results/2020-09-09-214445_21_VN_2050_A_results.xlsx'
    B: '../results/2020-09-09-181715_21_VN_2050_B_results.xlsx'
    I: '../results/2020-09-09-213723_21_VN_2050_I_results.xlsx'
    T: '../results/2020-09-09-181741_21_VN_2050_T_results.xlsx'
    OPN: '../results/2020-09-09-184148_21_VN_2050_OPN_results.xlsx'

