ForecastPeriod: 2050
Economies: 01_AUS
Scenario: Current #Current or Announced
#Solver: glpk # glpk or cbc
Name: v0.0.0 #Sector(s)vX.Y.Z; Sectors = AGR,BLD,IND,POW,REF,SUP,TRN,OWN,ALL
FilePaths:
## Results files ##
### Demand sectors ###
    #AGR: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_results.xlsx'
    #BLD: '../results/2020-08-09-122532_01_AUS_2050_BLDv0.1.0_results.xlsx'
    ##IND: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_results.xlsx'
    #TRN: '../results/2020-08-09-122706_01_AUS_2050_TRNv0.1.0_results.xlsx'
### Transformation and supply sectors ###
    #POW: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_results.xlsx'
    #REF: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_results.xlsx'
    #SUP: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_results.xlsx'

## Input data files ##  -- not working --
### Demand sectors ###
    AGR: '../results/2020-08-09-122350_01_AUS_2050_AGRv0.1.0_inputs.xlsx'
    BLD: '../results/2020-08-09-122532_01_AUS_2050_BLDv0.1.0_inputs.xlsx'
    #IND: '../results/2020-08-09-122350_01_AUS_2050_INDv0.1.0_inputs.xlsx'
    TRN: '../results/2020-08-09-122706_01_AUS_2050_TRNv0.1.0_inputs.xlsx'
### Transformation and supply sectors ###
    #POW: '../results/2020-08-09-122350_01_AUS_2050_POWv0.1.0_inputs.xlsx'
    #REF: '../results/2020-08-09-122350_01_AUS_2050_REFv0.1.0_inputs.xlsx'
    #SUP: '../results/2020-08-09-122350_01_AUS_2050_SUPv0.1.0_inputs.xlsx'
